const data = [
  {
    id: "1",
    category: "breakfast",
    title: "Easter Delight",
    img: "images/food2.png.webp",
    price: "52",
  },
  {
    id: "2",
    category: "launch",
    title: "Tiener Schnitze",
    img: "images/food3.png.webp",
    price: "32",
  },
  {
    id: "3",
    category: "launch",
    title: "Chicken Roast",
    img: "images/food4.png.webp",
    price: "86",
  },
  {
    id: "4",
    category: "breakfast",
    title: "Pork Sandwich",
    img: "images/food3.png.webp",
    price: "14",
  },
  {
    id: "5",
    category: "dinner",
    title: "Roasted Marrow",
    img: "images/food2.png.webp",
    price: "97",
  },
  {
    id: "6",
    category: "breakfast",
    title: "Easter Delight",
    img: "images/food2.png.webp",
    price: "48",
  },
  {
    id: "7",
    category: "launch",
    title: "Tiener Schnitze",
    img: "images/food3.png.webp",
    price: "78",
  },
  {
    id: "8",
    category: "launch",
    title: "Chicken Roast",
    img: "images/food4.png.webp",
    price: "96",
  },
  {
    id: "9",
    category: "breakfast",
    title: "Pork Sandwich",
    img: "images/food3.png.webp",
    price: "42",
  },
  {
    id: "10",
    category: "dinner",
    title: "Roasted Marrow",
    img: "images/food2.png.webp",
    price: "13",
  },
];
export default data;
